title               : Ghost OTPBOT
description         : >-                               # >- means to ignore newlines until "url:"
                      ghost-OTPBOT is the most advanced and versatile OTP & SMS capture bot that is capable of getting OTP & SMS codes from victims by impersonating a company or bank. You can use this to get OTP for logins, banks, credit cards, apple pay, and more.

url                 : "https://ghost-otpbot.github.io/"
repository          :  



exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
