title               : Ghost OTPBOT
description         : >-                               # >- means to ignore newlines until "url:"
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

url                 : "https://ghost-otpbot.github.io/"
repository          :  



exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
